import type { PortfolioData } from "./types"

export const mockPortfolioData: PortfolioData = {
  personalInfo: {
    name: "Kenneth Kebbie Kamara",
    title: "Software Engineer | Designer | Content Creator",
    bio: "Passionate about creating beautiful, functional digital experiences. I blend technical expertise with creative design to build solutions that make a difference.",
    email: "kenneth@example.com",
    phone: "+1 (555) 123-4567",
    location: "San Francisco, CA",
    avatar: "/professional-headshot.png",
    cvUrl: "/cv/kenneth-kamara-cv.pdf",
    socialLinks: [
      { platform: "GitHub", url: "https://github.com/kennethkamara", icon: "github" },
      { platform: "LinkedIn", url: "https://linkedin.com/in/kennethkamara", icon: "linkedin" },
      { platform: "Instagram", url: "https://instagram.com/kennethkamara", icon: "instagram" },
      { platform: "Dribbble", url: "https://dribbble.com/kennethkamara", icon: "dribbble" },
    ],
  },
  skills: [
    // Frontend
    { id: "1", name: "React", category: "frontend" },
    { id: "2", name: "Next.js", category: "frontend" },
    { id: "3", name: "TypeScript", category: "frontend" },
    { id: "4", name: "Tailwind CSS", category: "frontend" },
    // Backend
    { id: "5", name: "Node.js", category: "backend" },
    { id: "6", name: "Python", category: "backend" },
    // Database
    { id: "7", name: "PostgreSQL", category: "database" },
    { id: "8", name: "MongoDB", category: "database" },
    // Design
    { id: "9", name: "Figma", category: "design" },
    { id: "10", name: "Adobe XD", category: "design" },
    // Tools
    { id: "11", name: "Git", category: "tools" },
    { id: "12", name: "Docker", category: "tools" },
  ],
  projects: [
    {
      id: "1",
      title: "E-Commerce Platform",
      description:
        "A full-stack e-commerce solution with real-time inventory management, payment processing, and admin dashboard.",
      image: "/modern-ecommerce-website.png",
      technologies: ["Next.js", "TypeScript", "Stripe", "PostgreSQL", "Tailwind CSS"],
      liveUrl: "https://example.com",
      githubUrl: "https://github.com/kennethkamara/ecommerce",
      category: "web",
      featured: true,
      createdAt: "2024-01-15",
    },
    {
      id: "2",
      title: "Brand Identity Design",
      description:
        "Complete brand identity package including logo, color palette, typography, and brand guidelines for a tech startup.",
      image: "/brand-identity-design-mockup.jpg",
      technologies: ["Figma", "Illustrator", "Photoshop"],
      category: "design",
      featured: true,
      createdAt: "2024-02-20",
    },
    {
      id: "3",
      title: "Task Management App",
      description:
        "Collaborative task management application with real-time updates, team workspaces, and productivity analytics.",
      image: "/task-management-app.png",
      technologies: ["React", "Node.js", "Socket.io", "MongoDB"],
      liveUrl: "https://example.com",
      githubUrl: "https://github.com/kennethkamara/taskapp",
      category: "web",
      featured: true,
      createdAt: "2023-11-10",
    },
    {
      id: "4",
      title: "Animated Explainer Video",
      description:
        "Motion graphics explainer video for a SaaS product, showcasing features and benefits through engaging animations.",
      image: "/motion-graphics-animation-frame.jpg",
      technologies: ["After Effects", "Illustrator"],
      category: "animation",
      featured: false,
      createdAt: "2023-09-05",
    },
  ],
  experiences: [
    {
      id: "1",
      title: "Senior Software Engineer",
      company: "Tech Innovations Inc.",
      location: "San Francisco, CA",
      startDate: "2022-01",
      current: true,
      description: [
        "Lead development of customer-facing web applications using React and Next.js",
        "Mentor junior developers and conduct code reviews",
        "Collaborate with design team to implement pixel-perfect UI components",
        "Optimize application performance, reducing load times by 40%",
      ],
      type: "work",
    },
    {
      id: "2",
      title: "Full Stack Developer",
      company: "Digital Solutions Co.",
      location: "Remote",
      startDate: "2020-03",
      endDate: "2021-12",
      current: false,
      description: [
        "Built and maintained multiple client projects using MERN stack",
        "Implemented RESTful APIs and integrated third-party services",
        "Designed and developed responsive user interfaces",
        "Worked directly with clients to gather requirements and provide technical guidance",
      ],
      type: "work",
    },
    {
      id: "3",
      title: "UI/UX Designer",
      company: "Creative Studio",
      location: "New York, NY",
      startDate: "2018-06",
      endDate: "2020-02",
      current: false,
      description: [
        "Created user-centered designs for web and mobile applications",
        "Conducted user research and usability testing",
        "Developed design systems and component libraries",
        "Collaborated with developers to ensure design implementation",
      ],
      type: "work",
    },
    {
      id: "4",
      title: "Bachelor of Science in Computer Science",
      company: "University of California",
      location: "Berkeley, CA",
      startDate: "2014-09",
      endDate: "2018-05",
      current: false,
      description: [
        "Graduated with Honors (GPA: 3.8/4.0)",
        "Focus on Software Engineering and Human-Computer Interaction",
        "Led university coding club and organized hackathons",
        "Completed senior thesis on accessible web design",
      ],
      type: "education",
    },
    {
      id: "5",
      title: "Certified Web3Forms Developer",
      company: "Web3Forms Academy",
      location: "Online",
      startDate: "2025-08",
      endDate: "2025-08",
      current: false,
      description: [
        "Completed advanced form integration and email automation training",
        "Built secure contact workflows with Web3Forms, Next.js, and client-side validation",
      ],
      type: "certification",
    },
  ],
}
