from pathlib import Path

path = Path('public/cv/kenneth-kamara-cv.pdf')
content = b"""%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>
endobj
4 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
5 0 obj
<< /Length 176 >>
stream
BT
/F1 24 Tf
100 700 Td
(Portfolio CV) Tj
0 -36 Td
/F1 14 Tf
(\(This is a placeholder CV generated by the portfolio site.\)) Tj
0 -28 Td
(\(Replace this file with your real CV in public/cv/kenneth-kamara-cv.pdf\)) Tj
ET
endstream
endobj
xref
0 6
0000000000 65535 f 
0000000010 00000 n 
0000000060 00000 n 
0000000111 00000 n 
0000000180 00000 n 
0000000245 00000 n 
trailer
<< /Root 1 0 R /Size 6 >>
startxref
338
%%EOF
"""
path.write_bytes(content)
print('Created', path)
